In [0]:
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pickle

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
root_path = '/content/drive/My Drive/DSCI 303 Final Project/Data Trimming/'

In [0]:
with open('/content/drive/My Drive/DSCI 303 Final Project/Data_Trimming/preprocessed_150k_reviews.json') as json_file2: # Open json file to load
    data2 = json.load(json_file2)
    data3 = json.loads(data2)

In [0]:
df = pd.DataFrame.from_dict(data3)
X_raw = df['review']
Y_raw = df['stars']

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X_raw)

In [7]:
X

<150000x67816 sparse matrix of type '<class 'numpy.int64'>'
	with 6869739 stored elements in Compressed Sparse Row format>

In [0]:
Y = Y_raw

In [0]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score
# from sklearn.model_selection import GridSearchCV

In [0]:
from sklearn.model_selection import cross_val_score

In [0]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=101)

In [0]:
from sklearn import linear_model

In [0]:
# L2
svm = linear_model.SGDClassifier(max_iter=1000, tol=1e-3) # L2 penalty
svm_cv_scores = cross_val_score(svm, x_train, y_train, cv=8)
print(svm_cv_scores)

[0.64015732 0.6426     0.63726667 0.64553333 0.638      0.6404
 0.64226667 0.64424295]


In [0]:
np.average(np.array([0.64015732,0.6426,0.63726667,0.64553333,0.638,0.6404,0.64226667,0.64424295]))

0.6413083675

In [0]:
# L1
svm = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, penalty='l1') # L1 penalty
svm_cv_scores = cross_val_score(svm, x_train, y_train, cv=8)
print(svm_cv_scores)

[0.6130258  0.61826667 0.6214     0.6264     0.62173333 0.6192
 0.6182     0.62224148]


In [0]:
np.average(np.array([0.6130258,0.61826667,0.6214,0.6264,0.62173333,0.6192,0.6182,0.62224148]))

0.62005841

In [0]:
# elasticnet
svm = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, penalty='elasticnet') # elasticnet penalty
svm_cv_scores = cross_val_score(svm, x_train, y_train, cv=8)
print(svm_cv_scores)

[0.64255716 0.64353333 0.63613333 0.64826667 0.64566667 0.6394
 0.646      0.64397627]


In [0]:
np.average(np.array([0.64255716,0.64353333,0.63613333,0.64826667,0.64566667,0.6394,0.646,0.64397627]))

0.64319167875

In [13]:
# Support Vector Machine final
svm = linear_model.SGDClassifier(max_iter=1000, tol=1e-3, penalty='elasticnet')
svm.fit(x_train,y_train)
predsvm = svm.predict(x_test)
print("Confusion Matrix for Support Vector Machines:")
print(confusion_matrix(y_test,predsvm))
print("Score:",round(accuracy_score(y_test,predsvm)*100,2))
print("Classification Report:",classification_report(y_test,predsvm))

Confusion Matrix for Support Vector Machines:
[[ 3612   195   109   120   341]
 [  969   397   366   371   255]
 [  334   236   758  1278   646]
 [  127   102   325  2534  3595]
 [  150    23    96  1018 12043]]
Score: 64.48
Classification Report:               precision    recall  f1-score   support

         1.0       0.70      0.83      0.75      4377
         2.0       0.42      0.17      0.24      2358
         3.0       0.46      0.23      0.31      3252
         4.0       0.48      0.38      0.42      6683
         5.0       0.71      0.90      0.80     13330

    accuracy                           0.64     30000
   macro avg       0.55      0.50      0.50     30000
weighted avg       0.61      0.64      0.61     30000



In [0]:
pickle.dump(svm, open('svm.sav', 'wb'), protocol=2)
pickle.dump(vectorizer, open('vectorizer.sav', 'wb'), protocol=2)

In [0]:
file_dump = open("svm", 'wb')

pickle.dump(svm, file_dump)

In [0]:
file_read = open('svm', 'rb')
hi = pickle.load(file_read)

In [0]:
hi

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None,
              penalty='elasticnet', power_t=0.5, random_state=None,
              shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
              warm_start=False)